name: SERVER-CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app

    - name: SSH to SERVER and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app
          docker stop nodes-app || true
          docker rm nodejs-app || true
          docker run -d --name nodejs-app -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/nodejs-app
